#!/bin/sh
#SBATCH

# export OMP_NUM_THREADS=$nt

now=$(date '+%Y_%m_%d__%H_%M_%S')
mkdir $now
cd $now

../../../src/cli.o ../config.cfg ../mesh.mesh ../macro_restart_1000.txt
python3 ../../plot_res.py res.txt
