#!/bin/sh
#SBATCH

# export OMP_NUM_THREADS=$nt

now=$(date '+%Y_%m_%d__%H_%M_%S')
mkdir $now
cd $now

../../../src/cli.o ../config.cfg ../mesh_big.mesh ../macro_start.txt
# ../../../src/cli.o ../config.cfg ../mesh_big.mesh ../2025_06_04__13_06_07/restart.txt
python3 ../../plot_res.py res.txt
python3 ../../plot_channel.py macro_restart.txt



