#!/bin/sh
#SBATCH

now=$(date '+%Y_%m_%d__%H_%M_%S')
mkdir $now
cd $now

srun ../../../src/cli.o ../config.cfg ../mesh_very_coarse.mesh
srun python3 ../../plot_res.py
srun python3 ../../plot_surface.py