#!/bin/sh
#SBATCH

# export OMP_NUM_THREADS=$nt

now=$(date '+%Y_%m_%d__%H_%M_%S')
mkdir $now
cd $now

srun ../../../src/cli.o ../config.cfg ../mesh.mesh
srun python3 ../../plot.py res.txt
srun python3 ../../surface.py wall.txt

